version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  labels:
  - type/dependency-upgrade
  ignore:
  - dependency-name: io.micrometer:micrometer-core
    versions:
    - "> 1.5.0"
  rebase-strategy: disabled
