name: Check Netty SNAPSHOTS

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macOS - https://github.com/netty/netty/issues/9689
        # macOS - https://github.com/reactor/reactor-netty/issues/1171
        os: [ubuntu-18.04, windows-2019]
        transport: [native, nio]
        exclude:
          # excludes native on Windows (there's none)
          - os: windows-2019
            transport: native

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.2.0
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean check -PforceTransport=${{ matrix.transport }} -PforceNettyVersion='4.1.51.Final-SNAPSHOT'
