name: Check Codecov

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Update /etc/hosts file
        # /etc/hosts file needs to be updated as a workaround for
        # https://github.com/actions/virtual-environments/issues/3185
        run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew clean check --no-daemon
      - name: Codecov
        if: success()
        run: bash <(curl -s https://codecov.io/bash)